config/routes.rb
Rails.application.routes.draw do
  devise_for :profiles, controllers: { sessions: 'profiles/sessions', passwords: 'profiles/passwords',
                                    registrations: 'profiles/registrations' }
    root 'profile#home'
    get 'profile/:id' => 'profile#show', as: :profile
    delete 'profile/:id' => 'profile#destroy', as: :destroy_profile

    post 'profile/:id/add-partner' => 'profile#add_partner', as: :add_partner
    delete 'profile/:id/partner' => 'profile#remove_partner', as: :remove_partner
    post 'message/create' => 'message#create', as: :create_message

    delete 'profile/:id/get-message' => 'profile#get_message', as: :get_message
    delete 'message/:id/' => 'message#delete', as: :delete_message
    delete 'next-message' => 'profile#next_message'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WalkieTalkie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/layouts/layout.html.erb
<!-- To make layout work with extension part -->
<div class="container">
    <% if flash %>
        <div class="flash">
            <p class="notice"><%= flash[:notice] %></p>
            <p class="success"><%= flash[:success] %></p>
            <p class="error"><%= flash[:error] %><%= flash[:alert] %></p>
        </div>
    <% end %>

    <div class="header">
        <% if profile_signed_in? %>
            <%= link_to "Logout", destroy_profile_session_url, method: :delete %>
        <% else %>
            <%= link_to "Login", new_profile_session_url %>
            <%= link_to "Signup", new_profile_registration_url %>
        <% end %>
    </div>

    <%= render partial: @partial %>
</div>